name: Generate Tech Stack

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (if any for the script)
        run: |
          npm install octokit @actions/core @actions/github # Install Octokit for GitHub API, and actions/core/github for CI context

      - name: Generate Tech Stack
        run: |
          node scripts/generate-tech-stack.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ 'jackhoward24' }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/tech-stack.svg data/tech-stack.json || true # Add generated files, ignore if not exists yet
          git commit -m "feat: Generate tech stack and donut chart" || true # Commit if changes, ignore if no changes
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
